version: '3.8'

services:
  osrm-builder:
    image: osrm/osrm-backend
    container_name: osrm-data-builder
    volumes:
      - ./data:/data
    command: ["tail", "-f", "/dev/null"]

  osrm-routed:
    image: osrm/osrm-backend
    container_name: osrm-routing
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/sudeste-latest.osrm --max-table-size 5000
    restart: always