version: '3.8'

services:
  osrm-data-prep:
    image: osrm/osrm-backend:latest
    container_name: osrm-data-preparation
    volumes:
      - ./osrm-data:/data
    working_dir: /data
    command: >
      bash -c " if [ ! -f sao-paulo.osrm ]; then
        if [ ! -f sao-paulo.osm.pbf ]; then
          echo 'ERROR: sao-paulo.osm.pbf not found!' &&
          echo 'Please download it first with:' &&
          echo 'curl -L -o osrm-data/sao-paulo.osm.pbf https://download.openstreetmap.fr/extracts/south-america/brazil/southeast/sao-paulo.osm.pbf' &&
          exit 1
        fi &&
        echo 'Extracting road network...' &&
        osrm-extract -p /opt/car.lua sao-paulo.osm.pbf &&
        echo 'Partitioning network...' &&
        osrm-partition sao-paulo.osrm &&
        echo 'Customizing network...' &&
        osrm-customize sao-paulo.osrm &&
        echo 'Data preparation complete!' &&
        echo 'You can now delete sao-paulo.osm.pbf to save space'
      else
        echo 'Data already prepared, skipping...'
      fi "
    profiles:
      - prepare

  osrm-server:
    image: osrm/osrm-backend:latest
    platform: linux/amd64
    container_name: osrm-routing-server
    ports:
      - "5001:5000"
    volumes:
      - ./osrm-data:/data
    working_dir: /data
    command: osrm-routed --algorithm=mld sao-paulo.osrm --max-table-size 100000
    restart: unless-stopped

volumes:
  osrm-data:
