TWO_OPT_FREQUENCY = 25
COUNT_GENERATIONS_WITHOUT_IMPROVEMENT = 50
COUNT_GENERATIONS_WITHOUT_IMPROVEMENT_FOR_MUTATION = 10
DEFAULT_MUTATION_RATE = 0.05

TIME_DEPOT_STOP = 180

DEPOT_INDEX = 0

TOURNAMENT_SIZE = 5

DEFAULT_TIME_WEIGHT = 0.5
DEFAULT_DISTANCE_WEIGHT = 0.5

MUTATION_RATE_INCREASE_FACTOR = 1.1
MAX_MUTATION_RATE = 0.5

TWO_OPT_MUTATION_PROBABILITY = 0.5

MAX_IMPROVEMENTS_2OPT = 1
MAX_ITER_WITHOUT_IMPROVE_INTER_ROUTE = 3

DURATION_PENALTY_THRESHOLD = 0.9
DISTANCE_PENALTY_THRESHOLD = 0.9
PENALTY_MULTIPLIER = 5.0

OSRM_BASE_URL = "http://localhost:5001/table/v1/driving/"
POPULATION_SIZE = 50
POPULATION_HEURISTIC_TAX = 0.7
